### PR TITLE
Converted categories from comment time to FileTime

### PR DESCRIPTION
**Pull request by Kataiser**

### CODE REVIEW

**Comment by VampireFlower** [comment]
Is it not feasible to place them at the beginning of the file? The intent was so that visitors would see the end time front and center.

**Comment by Kataiser** [comment]
I mean it's standard to place them at the end, but at the start works too. would you prefer that?

**Comment by Kataiser** [comment]
ok assuming no answer equals yes

**Comment by VampireFlower** [comment]
> ok assuming no answer equals yes

you have no patience
but yes, it would be nicer at the top

**Pull request merged**
